public enum CaseDispositionDecisionCategoryCodeSimpleType {
    _216, _214, _208, _215, _203, _206, _211, _218, _212, _201, _217, _205, _207, _204, _210, _213, _219
}

public enum CaseDispositionDecisionCategoryCodeType {
    _216, _214, _208, _215, _203, _206, _211, _218, _212, _201, _217, _205, _207, _204, _210, _213, _219
}

public enum MilitaryDischargeCategoryCodeSimpleType {
    M, O, D, H, U, Q, G, N, B
}

public enum MilitaryDischargeCategoryCodeType {
    M, O, D, H, U, Q, G, N, B
}

public enum PleaCategoryCodeSimpleType {
    N, X, U, M, I, A, G, C
}

public enum PleaCategoryCodeType {
    N, X, U, M, I, A, G, C
}

public enum SupervisionLevelCodeSimpleType {
    _3_HIGH_RISK, COMPACT_OUT, FUGITIVE, _2_MODERATE_RISK, _4_EXTREME_RISK, ISP_II, _1_LOW_RISK, RESID_IN_STATE_CUSTD,
    ISP_I
}

public enum SupervisionLevelCodeType {
    _3_HIGH_RISK, COMPACT_OUT, FUGITIVE, _2_MODERATE_RISK, _4_EXTREME_RISK, ISP_II, _1_LOW_RISK, RESID_IN_STATE_CUSTD,
    ISP_I
}

public enum SupervisionRestrictionCodeSimpleType {
    ALCOHOL, CURFEW, EMPLOYMENT, VICIOUS_DOGS, STOLEN_VEHICLE, TRUTHFULNESS, NO_CONTACT_W_VICTM, EXPLOIT_MATERIAL,
    REGISTRATION_DNA, FREQUENT_SCHOOLS, FEES, SEARCHES, REPORTING, CONDUCT, EMPLOYMENT_VERIFY, LEAVE_COUNTY, RELEASE,
    ABSCONDING, CHILDREN_CONGREGATE, NOT_AT_COURT, MONTHLY_PAYMENTS, UNEMPLOYED, ELECTRONIC_MONITOR, SUBSTANCE_TESTING,
    HOME_VISITS, DISCONNECT_PHONE, SEX_STIMULUS_MATERIA, GANG_MEMBERS, DRUGS, DNA, NOT_DATE, SIGNS_GESTURES,
    PHONE_SERVICES, PAGER, CHEMICAL_ANALYSIS, ENTERTAIN_LURE, HMU_ABUSE, FIREARM_AMMUITION, ARREST_CITATIONS,
    ASSOCIATION, GED_DIPLOMA, INSIGNIAS_EMBLEMS, VISITS, THERAPY, PAINT_PENS, PORNOGRAPHY, DOCUMENTS_DATA_PHOTO,
    DRIVER_LICENSE_ID, SPECIAL, FREQUENT_GANG_PLACES, FIREARMS_USED, SUPERVISION_FEE, VEHICLE, TREATMENT_COUNSELING,
    LAW_ENFORCE_CONTACT, ALCOHOL_ESTABLISHMNT, RESIDENCE, POLYGRAPH, VICTIM_CONTACT, WEAPONS, INTERSTATE_COMPACT,
    CHILDREN_UNDER_18, PROVIDE_PHONE_LINE, FINANCIAL_AGREEMENT, NO_ALCOHOL, HMU_MOVE
}

public enum SupervisionRestrictionCodeType {
    ALCOHOL, CURFEW, EMPLOYMENT, VICIOUS_DOGS, STOLEN_VEHICLE, TRUTHFULNESS, NO_CONTACT_W_VICTM, EXPLOIT_MATERIAL,
    REGISTRATION_DNA, FREQUENT_SCHOOLS, FEES, SEARCHES, REPORTING, CONDUCT, EMPLOYMENT_VERIFY, LEAVE_COUNTY, RELEASE,
    ABSCONDING, CHILDREN_CONGREGATE, NOT_AT_COURT, MONTHLY_PAYMENTS, UNEMPLOYED, ELECTRONIC_MONITOR, SUBSTANCE_TESTING,
    HOME_VISITS, DISCONNECT_PHONE, SEX_STIMULUS_MATERIA, GANG_MEMBERS, DRUGS, DNA, NOT_DATE, SIGNS_GESTURES,
    PHONE_SERVICES, PAGER, CHEMICAL_ANALYSIS, ENTERTAIN_LURE, HMU_ABUSE, FIREARM_AMMUITION, ARREST_CITATIONS,
    ASSOCIATION, GED_DIPLOMA, INSIGNIAS_EMBLEMS, VISITS, THERAPY, PAINT_PENS, PORNOGRAPHY, DOCUMENTS_DATA_PHOTO,
    DRIVER_LICENSE_ID, SPECIAL, FREQUENT_GANG_PLACES, FIREARMS_USED,

SUPERMessage ChatGPT…
ChatGPT can
make mistakes.
Consider checking
important information.
?